#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TuitionMS.DAL
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="TuitionMs")]
	public partial class TuitionMSDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 可扩展性方法定义
    partial void OnCreated();
    partial void InsertAdministrator(Administrator instance);
    partial void UpdateAdministrator(Administrator instance);
    partial void DeleteAdministrator(Administrator instance);
    partial void InsertNotice(Notice instance);
    partial void UpdateNotice(Notice instance);
    partial void DeleteNotice(Notice instance);
    partial void InsertPropose(Propose instance);
    partial void UpdatePropose(Propose instance);
    partial void DeletePropose(Propose instance);
    partial void InsertClass(Class instance);
    partial void UpdateClass(Class instance);
    partial void DeleteClass(Class instance);
    partial void InsertDepartment(Department instance);
    partial void UpdateDepartment(Department instance);
    partial void DeleteDepartment(Department instance);
    partial void InsertSpeciality(Speciality instance);
    partial void UpdateSpeciality(Speciality instance);
    partial void DeleteSpeciality(Speciality instance);
    partial void InsertStudents(Students instance);
    partial void UpdateStudents(Students instance);
    partial void DeleteStudents(Students instance);
    partial void InsertTerm(Term instance);
    partial void UpdateTerm(Term instance);
    partial void DeleteTerm(Term instance);
    partial void InsertTuition(Tuition instance);
    partial void UpdateTuition(Tuition instance);
    partial void DeleteTuition(Tuition instance);
    partial void InsertStudTuition(StudTuition instance);
    partial void UpdateStudTuition(StudTuition instance);
    partial void DeleteStudTuition(StudTuition instance);
    #endregion
		
		public TuitionMSDataContext() : 
				base(global::TuitionMS.DAL.Properties.Settings.Default.TuitionMsConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public TuitionMSDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TuitionMSDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TuitionMSDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TuitionMSDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Administrator> Administrator
		{
			get
			{
				return this.GetTable<Administrator>();
			}
		}
		
		public System.Data.Linq.Table<Notice> Notice
		{
			get
			{
				return this.GetTable<Notice>();
			}
		}
		
		public System.Data.Linq.Table<Propose> Propose
		{
			get
			{
				return this.GetTable<Propose>();
			}
		}
		
		public System.Data.Linq.Table<Class> Class
		{
			get
			{
				return this.GetTable<Class>();
			}
		}
		
		public System.Data.Linq.Table<Department> Department
		{
			get
			{
				return this.GetTable<Department>();
			}
		}
		
		public System.Data.Linq.Table<Speciality> Speciality
		{
			get
			{
				return this.GetTable<Speciality>();
			}
		}
		
		public System.Data.Linq.Table<Students> Students
		{
			get
			{
				return this.GetTable<Students>();
			}
		}
		
		public System.Data.Linq.Table<Term> Term
		{
			get
			{
				return this.GetTable<Term>();
			}
		}
		
		public System.Data.Linq.Table<Tuition> Tuition
		{
			get
			{
				return this.GetTable<Tuition>();
			}
		}
		
		public System.Data.Linq.Table<StudTuition> StudTuition
		{
			get
			{
				return this.GetTable<StudTuition>();
			}
		}
		
		public System.Data.Linq.Table<Class_nopay_view> Class_nopay_view
		{
			get
			{
				return this.GetTable<Class_nopay_view>();
			}
		}
		
		public System.Data.Linq.Table<Class_statistics_view> Class_statistics_view
		{
			get
			{
				return this.GetTable<Class_statistics_view>();
			}
		}
		
		public System.Data.Linq.Table<Department_nopay_view> Department_nopay_view
		{
			get
			{
				return this.GetTable<Department_nopay_view>();
			}
		}
		
		public System.Data.Linq.Table<Department_statistics_view> Department_statistics_view
		{
			get
			{
				return this.GetTable<Department_statistics_view>();
			}
		}
		
		public System.Data.Linq.Table<Speciality_statistics_view> Speciality_statistics_view
		{
			get
			{
				return this.GetTable<Speciality_statistics_view>();
			}
		}
		
		public System.Data.Linq.Table<Student_infor_view> Student_infor_view
		{
			get
			{
				return this.GetTable<Student_infor_view>();
			}
		}
		
		public System.Data.Linq.Table<studentPayInformation> studentPayInformation
		{
			get
			{
				return this.GetTable<studentPayInformation>();
			}
		}
		
		public System.Data.Linq.Table<Term_statistics_view> Term_statistics_view
		{
			get
			{
				return this.GetTable<Term_statistics_view>();
			}
		}
		
		public System.Data.Linq.Table<TuiTion_seacher_view> TuiTion_seacher_view
		{
			get
			{
				return this.GetTable<TuiTion_seacher_view>();
			}
		}
		
		public System.Data.Linq.Table<Speciality_nopay_view> Speciality_nopay_view
		{
			get
			{
				return this.GetTable<Speciality_nopay_view>();
			}
		}
		
		public System.Data.Linq.Table<TuiTion_seacher_view_change> TuiTion_seacher_view_change
		{
			get
			{
				return this.GetTable<TuiTion_seacher_view_change>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Administrator")]
	public partial class Administrator : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _adminNo;
		
		private string _adminPwd;
		
		private string _adminType;
		
		private string _adminTel;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnadminNoChanging(string value);
    partial void OnadminNoChanged();
    partial void OnadminPwdChanging(string value);
    partial void OnadminPwdChanged();
    partial void OnadminTypeChanging(string value);
    partial void OnadminTypeChanged();
    partial void OnadminTelChanging(string value);
    partial void OnadminTelChanged();
    #endregion
		
		public Administrator()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_adminNo", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string adminNo
		{
			get
			{
				return this._adminNo;
			}
			set
			{
				if ((this._adminNo != value))
				{
					this.OnadminNoChanging(value);
					this.SendPropertyChanging();
					this._adminNo = value;
					this.SendPropertyChanged("adminNo");
					this.OnadminNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_adminPwd", DbType="VarChar(20)")]
		public string adminPwd
		{
			get
			{
				return this._adminPwd;
			}
			set
			{
				if ((this._adminPwd != value))
				{
					this.OnadminPwdChanging(value);
					this.SendPropertyChanging();
					this._adminPwd = value;
					this.SendPropertyChanged("adminPwd");
					this.OnadminPwdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_adminType", DbType="VarChar(20)")]
		public string adminType
		{
			get
			{
				return this._adminType;
			}
			set
			{
				if ((this._adminType != value))
				{
					this.OnadminTypeChanging(value);
					this.SendPropertyChanging();
					this._adminType = value;
					this.SendPropertyChanged("adminType");
					this.OnadminTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_adminTel", DbType="VarChar(20)")]
		public string adminTel
		{
			get
			{
				return this._adminTel;
			}
			set
			{
				if ((this._adminTel != value))
				{
					this.OnadminTelChanging(value);
					this.SendPropertyChanging();
					this._adminTel = value;
					this.SendPropertyChanged("adminTel");
					this.OnadminTelChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Notice")]
	public partial class Notice : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _notiObject;
		
		private string _notiContent;
		
		private System.Nullable<System.DateTime> _notiTime;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnnotiObjectChanging(string value);
    partial void OnnotiObjectChanged();
    partial void OnnotiContentChanging(string value);
    partial void OnnotiContentChanged();
    partial void OnnotiTimeChanging(System.Nullable<System.DateTime> value);
    partial void OnnotiTimeChanged();
    #endregion
		
		public Notice()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_notiObject", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string notiObject
		{
			get
			{
				return this._notiObject;
			}
			set
			{
				if ((this._notiObject != value))
				{
					this.OnnotiObjectChanging(value);
					this.SendPropertyChanging();
					this._notiObject = value;
					this.SendPropertyChanged("notiObject");
					this.OnnotiObjectChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_notiContent", DbType="NVarChar(MAX)")]
		public string notiContent
		{
			get
			{
				return this._notiContent;
			}
			set
			{
				if ((this._notiContent != value))
				{
					this.OnnotiContentChanging(value);
					this.SendPropertyChanging();
					this._notiContent = value;
					this.SendPropertyChanged("notiContent");
					this.OnnotiContentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_notiTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> notiTime
		{
			get
			{
				return this._notiTime;
			}
			set
			{
				if ((this._notiTime != value))
				{
					this.OnnotiTimeChanging(value);
					this.SendPropertyChanging();
					this._notiTime = value;
					this.SendPropertyChanged("notiTime");
					this.OnnotiTimeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Propose")]
	public partial class Propose : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _propObject;
		
		private string _propContent;
		
		private System.DateTime _propTime;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnpropObjectChanging(string value);
    partial void OnpropObjectChanged();
    partial void OnpropContentChanging(string value);
    partial void OnpropContentChanged();
    partial void OnpropTimeChanging(System.DateTime value);
    partial void OnpropTimeChanged();
    #endregion
		
		public Propose()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_propObject", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string propObject
		{
			get
			{
				return this._propObject;
			}
			set
			{
				if ((this._propObject != value))
				{
					this.OnpropObjectChanging(value);
					this.SendPropertyChanging();
					this._propObject = value;
					this.SendPropertyChanged("propObject");
					this.OnpropObjectChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_propContent", DbType="VarChar(MAX)")]
		public string propContent
		{
			get
			{
				return this._propContent;
			}
			set
			{
				if ((this._propContent != value))
				{
					this.OnpropContentChanging(value);
					this.SendPropertyChanging();
					this._propContent = value;
					this.SendPropertyChanged("propContent");
					this.OnpropContentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_propTime", DbType="DateTime NOT NULL", IsPrimaryKey=true)]
		public System.DateTime propTime
		{
			get
			{
				return this._propTime;
			}
			set
			{
				if ((this._propTime != value))
				{
					this.OnpropTimeChanging(value);
					this.SendPropertyChanging();
					this._propTime = value;
					this.SendPropertyChanged("propTime");
					this.OnpropTimeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Class")]
	public partial class Class : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _clasNo;
		
		private string _specNo;
		
		private string _clasName;
		
		private string _clasInstructor;
		
		private System.Nullable<int> _clasNum;
		
		private EntitySet<Students> _Students;
		
		private EntityRef<Speciality> _Speciality;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnclasNoChanging(string value);
    partial void OnclasNoChanged();
    partial void OnspecNoChanging(string value);
    partial void OnspecNoChanged();
    partial void OnclasNameChanging(string value);
    partial void OnclasNameChanged();
    partial void OnclasInstructorChanging(string value);
    partial void OnclasInstructorChanged();
    partial void OnclasNumChanging(System.Nullable<int> value);
    partial void OnclasNumChanged();
    #endregion
		
		public Class()
		{
			this._Students = new EntitySet<Students>(new Action<Students>(this.attach_Students), new Action<Students>(this.detach_Students));
			this._Speciality = default(EntityRef<Speciality>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_clasNo", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string clasNo
		{
			get
			{
				return this._clasNo;
			}
			set
			{
				if ((this._clasNo != value))
				{
					this.OnclasNoChanging(value);
					this.SendPropertyChanging();
					this._clasNo = value;
					this.SendPropertyChanged("clasNo");
					this.OnclasNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_specNo", DbType="VarChar(20)")]
		public string specNo
		{
			get
			{
				return this._specNo;
			}
			set
			{
				if ((this._specNo != value))
				{
					if (this._Speciality.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnspecNoChanging(value);
					this.SendPropertyChanging();
					this._specNo = value;
					this.SendPropertyChanged("specNo");
					this.OnspecNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_clasName", DbType="VarChar(50)")]
		public string clasName
		{
			get
			{
				return this._clasName;
			}
			set
			{
				if ((this._clasName != value))
				{
					this.OnclasNameChanging(value);
					this.SendPropertyChanging();
					this._clasName = value;
					this.SendPropertyChanged("clasName");
					this.OnclasNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_clasInstructor", DbType="VarChar(20)")]
		public string clasInstructor
		{
			get
			{
				return this._clasInstructor;
			}
			set
			{
				if ((this._clasInstructor != value))
				{
					this.OnclasInstructorChanging(value);
					this.SendPropertyChanging();
					this._clasInstructor = value;
					this.SendPropertyChanged("clasInstructor");
					this.OnclasInstructorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_clasNum", DbType="Int")]
		public System.Nullable<int> clasNum
		{
			get
			{
				return this._clasNum;
			}
			set
			{
				if ((this._clasNum != value))
				{
					this.OnclasNumChanging(value);
					this.SendPropertyChanging();
					this._clasNum = value;
					this.SendPropertyChanged("clasNum");
					this.OnclasNumChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Class_Students", Storage="_Students", ThisKey="clasNo", OtherKey="clasNo")]
		public EntitySet<Students> Students
		{
			get
			{
				return this._Students;
			}
			set
			{
				this._Students.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Speciality_Class", Storage="_Speciality", ThisKey="specNo", OtherKey="specNo", IsForeignKey=true)]
		public Speciality Speciality
		{
			get
			{
				return this._Speciality.Entity;
			}
			set
			{
				Speciality previousValue = this._Speciality.Entity;
				if (((previousValue != value) 
							|| (this._Speciality.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Speciality.Entity = null;
						previousValue.Class.Remove(this);
					}
					this._Speciality.Entity = value;
					if ((value != null))
					{
						value.Class.Add(this);
						this._specNo = value.specNo;
					}
					else
					{
						this._specNo = default(string);
					}
					this.SendPropertyChanged("Speciality");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Students(Students entity)
		{
			this.SendPropertyChanging();
			entity.Class = this;
		}
		
		private void detach_Students(Students entity)
		{
			this.SendPropertyChanging();
			entity.Class = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Department")]
	public partial class Department : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _deptNo;
		
		private string _deptName;
		
		private EntitySet<Speciality> _Speciality;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OndeptNoChanging(string value);
    partial void OndeptNoChanged();
    partial void OndeptNameChanging(string value);
    partial void OndeptNameChanged();
    #endregion
		
		public Department()
		{
			this._Speciality = new EntitySet<Speciality>(new Action<Speciality>(this.attach_Speciality), new Action<Speciality>(this.detach_Speciality));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_deptNo", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string deptNo
		{
			get
			{
				return this._deptNo;
			}
			set
			{
				if ((this._deptNo != value))
				{
					this.OndeptNoChanging(value);
					this.SendPropertyChanging();
					this._deptNo = value;
					this.SendPropertyChanged("deptNo");
					this.OndeptNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_deptName", DbType="VarChar(50)")]
		public string deptName
		{
			get
			{
				return this._deptName;
			}
			set
			{
				if ((this._deptName != value))
				{
					this.OndeptNameChanging(value);
					this.SendPropertyChanging();
					this._deptName = value;
					this.SendPropertyChanged("deptName");
					this.OndeptNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Department_Speciality", Storage="_Speciality", ThisKey="deptNo", OtherKey="deptNo")]
		public EntitySet<Speciality> Speciality
		{
			get
			{
				return this._Speciality;
			}
			set
			{
				this._Speciality.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Speciality(Speciality entity)
		{
			this.SendPropertyChanging();
			entity.Department = this;
		}
		
		private void detach_Speciality(Speciality entity)
		{
			this.SendPropertyChanging();
			entity.Department = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Speciality")]
	public partial class Speciality : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _specNo;
		
		private string _deptNo;
		
		private string _specName;
		
		private string _specManager;
		
		private EntitySet<Class> _Class;
		
		private EntitySet<Tuition> _Tuition;
		
		private EntityRef<Department> _Department;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnspecNoChanging(string value);
    partial void OnspecNoChanged();
    partial void OndeptNoChanging(string value);
    partial void OndeptNoChanged();
    partial void OnspecNameChanging(string value);
    partial void OnspecNameChanged();
    partial void OnspecManagerChanging(string value);
    partial void OnspecManagerChanged();
    #endregion
		
		public Speciality()
		{
			this._Class = new EntitySet<Class>(new Action<Class>(this.attach_Class), new Action<Class>(this.detach_Class));
			this._Tuition = new EntitySet<Tuition>(new Action<Tuition>(this.attach_Tuition), new Action<Tuition>(this.detach_Tuition));
			this._Department = default(EntityRef<Department>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_specNo", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string specNo
		{
			get
			{
				return this._specNo;
			}
			set
			{
				if ((this._specNo != value))
				{
					this.OnspecNoChanging(value);
					this.SendPropertyChanging();
					this._specNo = value;
					this.SendPropertyChanged("specNo");
					this.OnspecNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_deptNo", DbType="VarChar(20)")]
		public string deptNo
		{
			get
			{
				return this._deptNo;
			}
			set
			{
				if ((this._deptNo != value))
				{
					if (this._Department.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OndeptNoChanging(value);
					this.SendPropertyChanging();
					this._deptNo = value;
					this.SendPropertyChanged("deptNo");
					this.OndeptNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_specName", DbType="VarChar(50)")]
		public string specName
		{
			get
			{
				return this._specName;
			}
			set
			{
				if ((this._specName != value))
				{
					this.OnspecNameChanging(value);
					this.SendPropertyChanging();
					this._specName = value;
					this.SendPropertyChanged("specName");
					this.OnspecNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_specManager", DbType="VarChar(20)")]
		public string specManager
		{
			get
			{
				return this._specManager;
			}
			set
			{
				if ((this._specManager != value))
				{
					this.OnspecManagerChanging(value);
					this.SendPropertyChanging();
					this._specManager = value;
					this.SendPropertyChanged("specManager");
					this.OnspecManagerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Speciality_Class", Storage="_Class", ThisKey="specNo", OtherKey="specNo")]
		public EntitySet<Class> Class
		{
			get
			{
				return this._Class;
			}
			set
			{
				this._Class.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Speciality_Tuition", Storage="_Tuition", ThisKey="specNo", OtherKey="specNo")]
		public EntitySet<Tuition> Tuition
		{
			get
			{
				return this._Tuition;
			}
			set
			{
				this._Tuition.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Department_Speciality", Storage="_Department", ThisKey="deptNo", OtherKey="deptNo", IsForeignKey=true)]
		public Department Department
		{
			get
			{
				return this._Department.Entity;
			}
			set
			{
				Department previousValue = this._Department.Entity;
				if (((previousValue != value) 
							|| (this._Department.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Department.Entity = null;
						previousValue.Speciality.Remove(this);
					}
					this._Department.Entity = value;
					if ((value != null))
					{
						value.Speciality.Add(this);
						this._deptNo = value.deptNo;
					}
					else
					{
						this._deptNo = default(string);
					}
					this.SendPropertyChanged("Department");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Class(Class entity)
		{
			this.SendPropertyChanging();
			entity.Speciality = this;
		}
		
		private void detach_Class(Class entity)
		{
			this.SendPropertyChanging();
			entity.Speciality = null;
		}
		
		private void attach_Tuition(Tuition entity)
		{
			this.SendPropertyChanging();
			entity.Speciality = this;
		}
		
		private void detach_Tuition(Tuition entity)
		{
			this.SendPropertyChanging();
			entity.Speciality = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Students")]
	public partial class Students : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _studNo;
		
		private string _clasNo;
		
		private string _studName;
		
		private string _studPwd;
		
		private string _studBirth;
		
		private string _studTel;
		
		private string _studSex;
		
		private string _studEmail;
		
		private EntitySet<StudTuition> _StudTuition;
		
		private EntityRef<Class> _Class;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnstudNoChanging(string value);
    partial void OnstudNoChanged();
    partial void OnclasNoChanging(string value);
    partial void OnclasNoChanged();
    partial void OnstudNameChanging(string value);
    partial void OnstudNameChanged();
    partial void OnstudPwdChanging(string value);
    partial void OnstudPwdChanged();
    partial void OnstudBirthChanging(string value);
    partial void OnstudBirthChanged();
    partial void OnstudTelChanging(string value);
    partial void OnstudTelChanged();
    partial void OnstudSexChanging(string value);
    partial void OnstudSexChanged();
    partial void OnstudEmailChanging(string value);
    partial void OnstudEmailChanged();
    #endregion
		
		public Students()
		{
			this._StudTuition = new EntitySet<StudTuition>(new Action<StudTuition>(this.attach_StudTuition), new Action<StudTuition>(this.detach_StudTuition));
			this._Class = default(EntityRef<Class>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_studNo", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string studNo
		{
			get
			{
				return this._studNo;
			}
			set
			{
				if ((this._studNo != value))
				{
					this.OnstudNoChanging(value);
					this.SendPropertyChanging();
					this._studNo = value;
					this.SendPropertyChanged("studNo");
					this.OnstudNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_clasNo", DbType="VarChar(20)")]
		public string clasNo
		{
			get
			{
				return this._clasNo;
			}
			set
			{
				if ((this._clasNo != value))
				{
					if (this._Class.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnclasNoChanging(value);
					this.SendPropertyChanging();
					this._clasNo = value;
					this.SendPropertyChanged("clasNo");
					this.OnclasNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_studName", DbType="VarChar(50)")]
		public string studName
		{
			get
			{
				return this._studName;
			}
			set
			{
				if ((this._studName != value))
				{
					this.OnstudNameChanging(value);
					this.SendPropertyChanging();
					this._studName = value;
					this.SendPropertyChanged("studName");
					this.OnstudNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_studPwd", DbType="VarChar(20)")]
		public string studPwd
		{
			get
			{
				return this._studPwd;
			}
			set
			{
				if ((this._studPwd != value))
				{
					this.OnstudPwdChanging(value);
					this.SendPropertyChanging();
					this._studPwd = value;
					this.SendPropertyChanged("studPwd");
					this.OnstudPwdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_studBirth", DbType="VarChar(50)")]
		public string studBirth
		{
			get
			{
				return this._studBirth;
			}
			set
			{
				if ((this._studBirth != value))
				{
					this.OnstudBirthChanging(value);
					this.SendPropertyChanging();
					this._studBirth = value;
					this.SendPropertyChanged("studBirth");
					this.OnstudBirthChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_studTel", DbType="VarChar(15)")]
		public string studTel
		{
			get
			{
				return this._studTel;
			}
			set
			{
				if ((this._studTel != value))
				{
					this.OnstudTelChanging(value);
					this.SendPropertyChanging();
					this._studTel = value;
					this.SendPropertyChanged("studTel");
					this.OnstudTelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_studSex", DbType="VarChar(2)")]
		public string studSex
		{
			get
			{
				return this._studSex;
			}
			set
			{
				if ((this._studSex != value))
				{
					this.OnstudSexChanging(value);
					this.SendPropertyChanging();
					this._studSex = value;
					this.SendPropertyChanged("studSex");
					this.OnstudSexChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_studEmail", DbType="VarChar(50)")]
		public string studEmail
		{
			get
			{
				return this._studEmail;
			}
			set
			{
				if ((this._studEmail != value))
				{
					this.OnstudEmailChanging(value);
					this.SendPropertyChanging();
					this._studEmail = value;
					this.SendPropertyChanged("studEmail");
					this.OnstudEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Students_StudTuition", Storage="_StudTuition", ThisKey="studNo", OtherKey="studNo")]
		public EntitySet<StudTuition> StudTuition
		{
			get
			{
				return this._StudTuition;
			}
			set
			{
				this._StudTuition.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Class_Students", Storage="_Class", ThisKey="clasNo", OtherKey="clasNo", IsForeignKey=true)]
		public Class Class
		{
			get
			{
				return this._Class.Entity;
			}
			set
			{
				Class previousValue = this._Class.Entity;
				if (((previousValue != value) 
							|| (this._Class.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Class.Entity = null;
						previousValue.Students.Remove(this);
					}
					this._Class.Entity = value;
					if ((value != null))
					{
						value.Students.Add(this);
						this._clasNo = value.clasNo;
					}
					else
					{
						this._clasNo = default(string);
					}
					this.SendPropertyChanged("Class");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_StudTuition(StudTuition entity)
		{
			this.SendPropertyChanging();
			entity.Students = this;
		}
		
		private void detach_StudTuition(StudTuition entity)
		{
			this.SendPropertyChanging();
			entity.Students = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Term")]
	public partial class Term : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _termNo;
		
		private string _termName;
		
		private EntitySet<Tuition> _Tuition;
		
		private EntitySet<StudTuition> _StudTuition;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OntermNoChanging(string value);
    partial void OntermNoChanged();
    partial void OntermNameChanging(string value);
    partial void OntermNameChanged();
    #endregion
		
		public Term()
		{
			this._Tuition = new EntitySet<Tuition>(new Action<Tuition>(this.attach_Tuition), new Action<Tuition>(this.detach_Tuition));
			this._StudTuition = new EntitySet<StudTuition>(new Action<StudTuition>(this.attach_StudTuition), new Action<StudTuition>(this.detach_StudTuition));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_termNo", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string termNo
		{
			get
			{
				return this._termNo;
			}
			set
			{
				if ((this._termNo != value))
				{
					this.OntermNoChanging(value);
					this.SendPropertyChanging();
					this._termNo = value;
					this.SendPropertyChanged("termNo");
					this.OntermNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_termName", DbType="VarChar(20)")]
		public string termName
		{
			get
			{
				return this._termName;
			}
			set
			{
				if ((this._termName != value))
				{
					this.OntermNameChanging(value);
					this.SendPropertyChanging();
					this._termName = value;
					this.SendPropertyChanged("termName");
					this.OntermNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Term_Tuition", Storage="_Tuition", ThisKey="termNo", OtherKey="termNo")]
		public EntitySet<Tuition> Tuition
		{
			get
			{
				return this._Tuition;
			}
			set
			{
				this._Tuition.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Term_StudTuition", Storage="_StudTuition", ThisKey="termNo", OtherKey="termNo")]
		public EntitySet<StudTuition> StudTuition
		{
			get
			{
				return this._StudTuition;
			}
			set
			{
				this._StudTuition.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Tuition(Tuition entity)
		{
			this.SendPropertyChanging();
			entity.Term = this;
		}
		
		private void detach_Tuition(Tuition entity)
		{
			this.SendPropertyChanging();
			entity.Term = null;
		}
		
		private void attach_StudTuition(StudTuition entity)
		{
			this.SendPropertyChanging();
			entity.Term = this;
		}
		
		private void detach_StudTuition(StudTuition entity)
		{
			this.SendPropertyChanging();
			entity.Term = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tuition")]
	public partial class Tuition : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _termNo;
		
		private string _specNo;
		
		private System.Nullable<int> _tuition1;
		
		private System.Nullable<int> _premiun;
		
		private System.Nullable<int> _accom;
		
		private System.Nullable<int> _book;
		
		private System.Nullable<int> _other;
		
		private System.Nullable<int> _total;
		
		private EntityRef<Term> _Term;
		
		private EntityRef<Speciality> _Speciality;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OntermNoChanging(string value);
    partial void OntermNoChanged();
    partial void OnspecNoChanging(string value);
    partial void OnspecNoChanged();
    partial void Ontuition1Changing(System.Nullable<int> value);
    partial void Ontuition1Changed();
    partial void OnpremiunChanging(System.Nullable<int> value);
    partial void OnpremiunChanged();
    partial void OnaccomChanging(System.Nullable<int> value);
    partial void OnaccomChanged();
    partial void OnbookChanging(System.Nullable<int> value);
    partial void OnbookChanged();
    partial void OnotherChanging(System.Nullable<int> value);
    partial void OnotherChanged();
    partial void OntotalChanging(System.Nullable<int> value);
    partial void OntotalChanged();
    #endregion
		
		public Tuition()
		{
			this._Term = default(EntityRef<Term>);
			this._Speciality = default(EntityRef<Speciality>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_termNo", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string termNo
		{
			get
			{
				return this._termNo;
			}
			set
			{
				if ((this._termNo != value))
				{
					if (this._Term.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OntermNoChanging(value);
					this.SendPropertyChanging();
					this._termNo = value;
					this.SendPropertyChanged("termNo");
					this.OntermNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_specNo", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string specNo
		{
			get
			{
				return this._specNo;
			}
			set
			{
				if ((this._specNo != value))
				{
					if (this._Speciality.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnspecNoChanging(value);
					this.SendPropertyChanging();
					this._specNo = value;
					this.SendPropertyChanged("specNo");
					this.OnspecNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="tuition", Storage="_tuition1", DbType="Int")]
		public System.Nullable<int> tuition1
		{
			get
			{
				return this._tuition1;
			}
			set
			{
				if ((this._tuition1 != value))
				{
					this.Ontuition1Changing(value);
					this.SendPropertyChanging();
					this._tuition1 = value;
					this.SendPropertyChanged("tuition1");
					this.Ontuition1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_premiun", DbType="Int")]
		public System.Nullable<int> premiun
		{
			get
			{
				return this._premiun;
			}
			set
			{
				if ((this._premiun != value))
				{
					this.OnpremiunChanging(value);
					this.SendPropertyChanging();
					this._premiun = value;
					this.SendPropertyChanged("premiun");
					this.OnpremiunChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_accom", DbType="Int")]
		public System.Nullable<int> accom
		{
			get
			{
				return this._accom;
			}
			set
			{
				if ((this._accom != value))
				{
					this.OnaccomChanging(value);
					this.SendPropertyChanging();
					this._accom = value;
					this.SendPropertyChanged("accom");
					this.OnaccomChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_book", DbType="Int")]
		public System.Nullable<int> book
		{
			get
			{
				return this._book;
			}
			set
			{
				if ((this._book != value))
				{
					this.OnbookChanging(value);
					this.SendPropertyChanging();
					this._book = value;
					this.SendPropertyChanged("book");
					this.OnbookChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_other", DbType="Int")]
		public System.Nullable<int> other
		{
			get
			{
				return this._other;
			}
			set
			{
				if ((this._other != value))
				{
					this.OnotherChanging(value);
					this.SendPropertyChanging();
					this._other = value;
					this.SendPropertyChanged("other");
					this.OnotherChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_total", DbType="Int")]
		public System.Nullable<int> total
		{
			get
			{
				return this._total;
			}
			set
			{
				if ((this._total != value))
				{
					this.OntotalChanging(value);
					this.SendPropertyChanging();
					this._total = value;
					this.SendPropertyChanged("total");
					this.OntotalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Term_Tuition", Storage="_Term", ThisKey="termNo", OtherKey="termNo", IsForeignKey=true)]
		public Term Term
		{
			get
			{
				return this._Term.Entity;
			}
			set
			{
				Term previousValue = this._Term.Entity;
				if (((previousValue != value) 
							|| (this._Term.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Term.Entity = null;
						previousValue.Tuition.Remove(this);
					}
					this._Term.Entity = value;
					if ((value != null))
					{
						value.Tuition.Add(this);
						this._termNo = value.termNo;
					}
					else
					{
						this._termNo = default(string);
					}
					this.SendPropertyChanged("Term");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Speciality_Tuition", Storage="_Speciality", ThisKey="specNo", OtherKey="specNo", IsForeignKey=true)]
		public Speciality Speciality
		{
			get
			{
				return this._Speciality.Entity;
			}
			set
			{
				Speciality previousValue = this._Speciality.Entity;
				if (((previousValue != value) 
							|| (this._Speciality.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Speciality.Entity = null;
						previousValue.Tuition.Remove(this);
					}
					this._Speciality.Entity = value;
					if ((value != null))
					{
						value.Tuition.Add(this);
						this._specNo = value.specNo;
					}
					else
					{
						this._specNo = default(string);
					}
					this.SendPropertyChanged("Speciality");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.StudTuition")]
	public partial class StudTuition : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _termNo;
		
		private string _studNo;
		
		private System.Nullable<int> _sPremiun;
		
		private System.Nullable<int> _sAccom;
		
		private System.Nullable<int> _sBook;
		
		private System.Nullable<int> _sOther;
		
		private System.Nullable<int> _sTuiWaiver;
		
		private System.Nullable<int> _sLoans;
		
		private System.Nullable<int> _sRealPay;
		
		private System.Nullable<int> _sRealCharge;
		
		private string _sData;
		
		private System.Nullable<int> _sTuition;
		
		private EntityRef<Students> _Students;
		
		private EntityRef<Term> _Term;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OntermNoChanging(string value);
    partial void OntermNoChanged();
    partial void OnstudNoChanging(string value);
    partial void OnstudNoChanged();
    partial void OnsPremiunChanging(System.Nullable<int> value);
    partial void OnsPremiunChanged();
    partial void OnsAccomChanging(System.Nullable<int> value);
    partial void OnsAccomChanged();
    partial void OnsBookChanging(System.Nullable<int> value);
    partial void OnsBookChanged();
    partial void OnsOtherChanging(System.Nullable<int> value);
    partial void OnsOtherChanged();
    partial void OnsTuiWaiverChanging(System.Nullable<int> value);
    partial void OnsTuiWaiverChanged();
    partial void OnsLoansChanging(System.Nullable<int> value);
    partial void OnsLoansChanged();
    partial void OnsRealPayChanging(System.Nullable<int> value);
    partial void OnsRealPayChanged();
    partial void OnsRealChargeChanging(System.Nullable<int> value);
    partial void OnsRealChargeChanged();
    partial void OnsDataChanging(string value);
    partial void OnsDataChanged();
    partial void OnsTuitionChanging(System.Nullable<int> value);
    partial void OnsTuitionChanged();
    #endregion
		
		public StudTuition()
		{
			this._Students = default(EntityRef<Students>);
			this._Term = default(EntityRef<Term>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_termNo", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string termNo
		{
			get
			{
				return this._termNo;
			}
			set
			{
				if ((this._termNo != value))
				{
					if (this._Term.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OntermNoChanging(value);
					this.SendPropertyChanging();
					this._termNo = value;
					this.SendPropertyChanged("termNo");
					this.OntermNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_studNo", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string studNo
		{
			get
			{
				return this._studNo;
			}
			set
			{
				if ((this._studNo != value))
				{
					if (this._Students.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnstudNoChanging(value);
					this.SendPropertyChanging();
					this._studNo = value;
					this.SendPropertyChanged("studNo");
					this.OnstudNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sPremiun", DbType="Int")]
		public System.Nullable<int> sPremiun
		{
			get
			{
				return this._sPremiun;
			}
			set
			{
				if ((this._sPremiun != value))
				{
					this.OnsPremiunChanging(value);
					this.SendPropertyChanging();
					this._sPremiun = value;
					this.SendPropertyChanged("sPremiun");
					this.OnsPremiunChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sAccom", DbType="Int")]
		public System.Nullable<int> sAccom
		{
			get
			{
				return this._sAccom;
			}
			set
			{
				if ((this._sAccom != value))
				{
					this.OnsAccomChanging(value);
					this.SendPropertyChanging();
					this._sAccom = value;
					this.SendPropertyChanged("sAccom");
					this.OnsAccomChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sBook", DbType="Int")]
		public System.Nullable<int> sBook
		{
			get
			{
				return this._sBook;
			}
			set
			{
				if ((this._sBook != value))
				{
					this.OnsBookChanging(value);
					this.SendPropertyChanging();
					this._sBook = value;
					this.SendPropertyChanged("sBook");
					this.OnsBookChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sOther", DbType="Int")]
		public System.Nullable<int> sOther
		{
			get
			{
				return this._sOther;
			}
			set
			{
				if ((this._sOther != value))
				{
					this.OnsOtherChanging(value);
					this.SendPropertyChanging();
					this._sOther = value;
					this.SendPropertyChanged("sOther");
					this.OnsOtherChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sTuiWaiver", DbType="Int")]
		public System.Nullable<int> sTuiWaiver
		{
			get
			{
				return this._sTuiWaiver;
			}
			set
			{
				if ((this._sTuiWaiver != value))
				{
					this.OnsTuiWaiverChanging(value);
					this.SendPropertyChanging();
					this._sTuiWaiver = value;
					this.SendPropertyChanged("sTuiWaiver");
					this.OnsTuiWaiverChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sLoans", DbType="Int")]
		public System.Nullable<int> sLoans
		{
			get
			{
				return this._sLoans;
			}
			set
			{
				if ((this._sLoans != value))
				{
					this.OnsLoansChanging(value);
					this.SendPropertyChanging();
					this._sLoans = value;
					this.SendPropertyChanged("sLoans");
					this.OnsLoansChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sRealPay", DbType="Int")]
		public System.Nullable<int> sRealPay
		{
			get
			{
				return this._sRealPay;
			}
			set
			{
				if ((this._sRealPay != value))
				{
					this.OnsRealPayChanging(value);
					this.SendPropertyChanging();
					this._sRealPay = value;
					this.SendPropertyChanged("sRealPay");
					this.OnsRealPayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sRealCharge", DbType="Int")]
		public System.Nullable<int> sRealCharge
		{
			get
			{
				return this._sRealCharge;
			}
			set
			{
				if ((this._sRealCharge != value))
				{
					this.OnsRealChargeChanging(value);
					this.SendPropertyChanging();
					this._sRealCharge = value;
					this.SendPropertyChanged("sRealCharge");
					this.OnsRealChargeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sData", DbType="VarChar(50)")]
		public string sData
		{
			get
			{
				return this._sData;
			}
			set
			{
				if ((this._sData != value))
				{
					this.OnsDataChanging(value);
					this.SendPropertyChanging();
					this._sData = value;
					this.SendPropertyChanged("sData");
					this.OnsDataChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sTuition", DbType="Int")]
		public System.Nullable<int> sTuition
		{
			get
			{
				return this._sTuition;
			}
			set
			{
				if ((this._sTuition != value))
				{
					this.OnsTuitionChanging(value);
					this.SendPropertyChanging();
					this._sTuition = value;
					this.SendPropertyChanged("sTuition");
					this.OnsTuitionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Students_StudTuition", Storage="_Students", ThisKey="studNo", OtherKey="studNo", IsForeignKey=true)]
		public Students Students
		{
			get
			{
				return this._Students.Entity;
			}
			set
			{
				Students previousValue = this._Students.Entity;
				if (((previousValue != value) 
							|| (this._Students.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Students.Entity = null;
						previousValue.StudTuition.Remove(this);
					}
					this._Students.Entity = value;
					if ((value != null))
					{
						value.StudTuition.Add(this);
						this._studNo = value.studNo;
					}
					else
					{
						this._studNo = default(string);
					}
					this.SendPropertyChanged("Students");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Term_StudTuition", Storage="_Term", ThisKey="termNo", OtherKey="termNo", IsForeignKey=true)]
		public Term Term
		{
			get
			{
				return this._Term.Entity;
			}
			set
			{
				Term previousValue = this._Term.Entity;
				if (((previousValue != value) 
							|| (this._Term.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Term.Entity = null;
						previousValue.StudTuition.Remove(this);
					}
					this._Term.Entity = value;
					if ((value != null))
					{
						value.StudTuition.Add(this);
						this._termNo = value.termNo;
					}
					else
					{
						this._termNo = default(string);
					}
					this.SendPropertyChanged("Term");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Class_nopay_view")]
	public partial class Class_nopay_view
	{
		
		private string _班级;
		
		private string _专业;
		
		private System.Nullable<int> _学费欠费总额;
		
		private System.Nullable<int> _保险费欠费总额;
		
		private System.Nullable<int> _住宿费欠费总额;
		
		private System.Nullable<int> _书本费欠费总额;
		
		private System.Nullable<int> _其他费欠费总额;
		
		private System.Nullable<int> _减免欠费总额;
		
		private System.Nullable<int> _贷款欠费总额;
		
		private System.Nullable<int> _总人数;
		
		public Class_nopay_view()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_班级", DbType="VarChar(50)")]
		public string 班级
		{
			get
			{
				return this._班级;
			}
			set
			{
				if ((this._班级 != value))
				{
					this._班级 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_专业", DbType="VarChar(50)")]
		public string 专业
		{
			get
			{
				return this._专业;
			}
			set
			{
				if ((this._专业 != value))
				{
					this._专业 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_学费欠费总额", DbType="Int")]
		public System.Nullable<int> 学费欠费总额
		{
			get
			{
				return this._学费欠费总额;
			}
			set
			{
				if ((this._学费欠费总额 != value))
				{
					this._学费欠费总额 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_保险费欠费总额", DbType="Int")]
		public System.Nullable<int> 保险费欠费总额
		{
			get
			{
				return this._保险费欠费总额;
			}
			set
			{
				if ((this._保险费欠费总额 != value))
				{
					this._保险费欠费总额 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_住宿费欠费总额", DbType="Int")]
		public System.Nullable<int> 住宿费欠费总额
		{
			get
			{
				return this._住宿费欠费总额;
			}
			set
			{
				if ((this._住宿费欠费总额 != value))
				{
					this._住宿费欠费总额 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_书本费欠费总额", DbType="Int")]
		public System.Nullable<int> 书本费欠费总额
		{
			get
			{
				return this._书本费欠费总额;
			}
			set
			{
				if ((this._书本费欠费总额 != value))
				{
					this._书本费欠费总额 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_其他费欠费总额", DbType="Int")]
		public System.Nullable<int> 其他费欠费总额
		{
			get
			{
				return this._其他费欠费总额;
			}
			set
			{
				if ((this._其他费欠费总额 != value))
				{
					this._其他费欠费总额 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_减免欠费总额", DbType="Int")]
		public System.Nullable<int> 减免欠费总额
		{
			get
			{
				return this._减免欠费总额;
			}
			set
			{
				if ((this._减免欠费总额 != value))
				{
					this._减免欠费总额 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_贷款欠费总额", DbType="Int")]
		public System.Nullable<int> 贷款欠费总额
		{
			get
			{
				return this._贷款欠费总额;
			}
			set
			{
				if ((this._贷款欠费总额 != value))
				{
					this._贷款欠费总额 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_总人数", DbType="Int")]
		public System.Nullable<int> 总人数
		{
			get
			{
				return this._总人数;
			}
			set
			{
				if ((this._总人数 != value))
				{
					this._总人数 = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Class_statistics_view")]
	public partial class Class_statistics_view
	{
		
		private string _班级;
		
		private System.Nullable<int> _学费总和;
		
		private System.Nullable<int> _保险费总和;
		
		private System.Nullable<int> _住宿费总和;
		
		private System.Nullable<int> _书本费总和;
		
		private System.Nullable<int> _其他费总和;
		
		private System.Nullable<int> _减免总和;
		
		private System.Nullable<int> _贷款总和;
		
		private System.Nullable<int> _实缴总和;
		
		private System.Nullable<int> _实收总和;
		
		private System.Nullable<int> _总人数;
		
		public Class_statistics_view()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_班级", DbType="VarChar(50)")]
		public string 班级
		{
			get
			{
				return this._班级;
			}
			set
			{
				if ((this._班级 != value))
				{
					this._班级 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_学费总和", DbType="Int")]
		public System.Nullable<int> 学费总和
		{
			get
			{
				return this._学费总和;
			}
			set
			{
				if ((this._学费总和 != value))
				{
					this._学费总和 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_保险费总和", DbType="Int")]
		public System.Nullable<int> 保险费总和
		{
			get
			{
				return this._保险费总和;
			}
			set
			{
				if ((this._保险费总和 != value))
				{
					this._保险费总和 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_住宿费总和", DbType="Int")]
		public System.Nullable<int> 住宿费总和
		{
			get
			{
				return this._住宿费总和;
			}
			set
			{
				if ((this._住宿费总和 != value))
				{
					this._住宿费总和 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_书本费总和", DbType="Int")]
		public System.Nullable<int> 书本费总和
		{
			get
			{
				return this._书本费总和;
			}
			set
			{
				if ((this._书本费总和 != value))
				{
					this._书本费总和 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_其他费总和", DbType="Int")]
		public System.Nullable<int> 其他费总和
		{
			get
			{
				return this._其他费总和;
			}
			set
			{
				if ((this._其他费总和 != value))
				{
					this._其他费总和 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_减免总和", DbType="Int")]
		public System.Nullable<int> 减免总和
		{
			get
			{
				return this._减免总和;
			}
			set
			{
				if ((this._减免总和 != value))
				{
					this._减免总和 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_贷款总和", DbType="Int")]
		public System.Nullable<int> 贷款总和
		{
			get
			{
				return this._贷款总和;
			}
			set
			{
				if ((this._贷款总和 != value))
				{
					this._贷款总和 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_实缴总和", DbType="Int")]
		public System.Nullable<int> 实缴总和
		{
			get
			{
				return this._实缴总和;
			}
			set
			{
				if ((this._实缴总和 != value))
				{
					this._实缴总和 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_实收总和", DbType="Int")]
		public System.Nullable<int> 实收总和
		{
			get
			{
				return this._实收总和;
			}
			set
			{
				if ((this._实收总和 != value))
				{
					this._实收总和 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_总人数", DbType="Int")]
		public System.Nullable<int> 总人数
		{
			get
			{
				return this._总人数;
			}
			set
			{
				if ((this._总人数 != value))
				{
					this._总人数 = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Department_nopay_view")]
	public partial class Department_nopay_view
	{
		
		private string _学院;
		
		private System.Nullable<int> _学费欠费总额;
		
		private System.Nullable<int> _保险费欠费总额;
		
		private System.Nullable<int> _住宿费欠费总额;
		
		private System.Nullable<int> _书本费欠费总额;
		
		private System.Nullable<int> _其他费欠费总额;
		
		private System.Nullable<int> _减免欠费总额;
		
		private System.Nullable<int> _贷款欠费总额;
		
		private System.Nullable<int> _总人数;
		
		public Department_nopay_view()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_学院", DbType="VarChar(50)")]
		public string 学院
		{
			get
			{
				return this._学院;
			}
			set
			{
				if ((this._学院 != value))
				{
					this._学院 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_学费欠费总额", DbType="Int")]
		public System.Nullable<int> 学费欠费总额
		{
			get
			{
				return this._学费欠费总额;
			}
			set
			{
				if ((this._学费欠费总额 != value))
				{
					this._学费欠费总额 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_保险费欠费总额", DbType="Int")]
		public System.Nullable<int> 保险费欠费总额
		{
			get
			{
				return this._保险费欠费总额;
			}
			set
			{
				if ((this._保险费欠费总额 != value))
				{
					this._保险费欠费总额 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_住宿费欠费总额", DbType="Int")]
		public System.Nullable<int> 住宿费欠费总额
		{
			get
			{
				return this._住宿费欠费总额;
			}
			set
			{
				if ((this._住宿费欠费总额 != value))
				{
					this._住宿费欠费总额 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_书本费欠费总额", DbType="Int")]
		public System.Nullable<int> 书本费欠费总额
		{
			get
			{
				return this._书本费欠费总额;
			}
			set
			{
				if ((this._书本费欠费总额 != value))
				{
					this._书本费欠费总额 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_其他费欠费总额", DbType="Int")]
		public System.Nullable<int> 其他费欠费总额
		{
			get
			{
				return this._其他费欠费总额;
			}
			set
			{
				if ((this._其他费欠费总额 != value))
				{
					this._其他费欠费总额 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_减免欠费总额", DbType="Int")]
		public System.Nullable<int> 减免欠费总额
		{
			get
			{
				return this._减免欠费总额;
			}
			set
			{
				if ((this._减免欠费总额 != value))
				{
					this._减免欠费总额 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_贷款欠费总额", DbType="Int")]
		public System.Nullable<int> 贷款欠费总额
		{
			get
			{
				return this._贷款欠费总额;
			}
			set
			{
				if ((this._贷款欠费总额 != value))
				{
					this._贷款欠费总额 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_总人数", DbType="Int")]
		public System.Nullable<int> 总人数
		{
			get
			{
				return this._总人数;
			}
			set
			{
				if ((this._总人数 != value))
				{
					this._总人数 = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Department_statistics_view")]
	public partial class Department_statistics_view
	{
		
		private string _学院;
		
		private System.Nullable<int> _学费总和;
		
		private System.Nullable<int> _保险费总和;
		
		private System.Nullable<int> _住宿费总和;
		
		private System.Nullable<int> _书本费总和;
		
		private System.Nullable<int> _其他费总和;
		
		private System.Nullable<int> _减免总和;
		
		private System.Nullable<int> _贷款总和;
		
		private System.Nullable<int> _实缴总和;
		
		private System.Nullable<int> _实收总和;
		
		private System.Nullable<int> _总人数;
		
		public Department_statistics_view()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_学院", DbType="VarChar(50)")]
		public string 学院
		{
			get
			{
				return this._学院;
			}
			set
			{
				if ((this._学院 != value))
				{
					this._学院 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_学费总和", DbType="Int")]
		public System.Nullable<int> 学费总和
		{
			get
			{
				return this._学费总和;
			}
			set
			{
				if ((this._学费总和 != value))
				{
					this._学费总和 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_保险费总和", DbType="Int")]
		public System.Nullable<int> 保险费总和
		{
			get
			{
				return this._保险费总和;
			}
			set
			{
				if ((this._保险费总和 != value))
				{
					this._保险费总和 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_住宿费总和", DbType="Int")]
		public System.Nullable<int> 住宿费总和
		{
			get
			{
				return this._住宿费总和;
			}
			set
			{
				if ((this._住宿费总和 != value))
				{
					this._住宿费总和 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_书本费总和", DbType="Int")]
		public System.Nullable<int> 书本费总和
		{
			get
			{
				return this._书本费总和;
			}
			set
			{
				if ((this._书本费总和 != value))
				{
					this._书本费总和 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_其他费总和", DbType="Int")]
		public System.Nullable<int> 其他费总和
		{
			get
			{
				return this._其他费总和;
			}
			set
			{
				if ((this._其他费总和 != value))
				{
					this._其他费总和 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_减免总和", DbType="Int")]
		public System.Nullable<int> 减免总和
		{
			get
			{
				return this._减免总和;
			}
			set
			{
				if ((this._减免总和 != value))
				{
					this._减免总和 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_贷款总和", DbType="Int")]
		public System.Nullable<int> 贷款总和
		{
			get
			{
				return this._贷款总和;
			}
			set
			{
				if ((this._贷款总和 != value))
				{
					this._贷款总和 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_实缴总和", DbType="Int")]
		public System.Nullable<int> 实缴总和
		{
			get
			{
				return this._实缴总和;
			}
			set
			{
				if ((this._实缴总和 != value))
				{
					this._实缴总和 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_实收总和", DbType="Int")]
		public System.Nullable<int> 实收总和
		{
			get
			{
				return this._实收总和;
			}
			set
			{
				if ((this._实收总和 != value))
				{
					this._实收总和 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_总人数", DbType="Int")]
		public System.Nullable<int> 总人数
		{
			get
			{
				return this._总人数;
			}
			set
			{
				if ((this._总人数 != value))
				{
					this._总人数 = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Speciality_statistics_view")]
	public partial class Speciality_statistics_view
	{
		
		private string _专业;
		
		private System.Nullable<int> _学费总和;
		
		private System.Nullable<int> _保险费总和;
		
		private System.Nullable<int> _住宿费总和;
		
		private System.Nullable<int> _书本费总和;
		
		private System.Nullable<int> _其他费总和;
		
		private System.Nullable<int> _减免总和;
		
		private System.Nullable<int> _贷款总和;
		
		private System.Nullable<int> _实缴总和;
		
		private System.Nullable<int> _实收总和;
		
		private System.Nullable<int> _总人数;
		
		public Speciality_statistics_view()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_专业", DbType="VarChar(50)")]
		public string 专业
		{
			get
			{
				return this._专业;
			}
			set
			{
				if ((this._专业 != value))
				{
					this._专业 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_学费总和", DbType="Int")]
		public System.Nullable<int> 学费总和
		{
			get
			{
				return this._学费总和;
			}
			set
			{
				if ((this._学费总和 != value))
				{
					this._学费总和 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_保险费总和", DbType="Int")]
		public System.Nullable<int> 保险费总和
		{
			get
			{
				return this._保险费总和;
			}
			set
			{
				if ((this._保险费总和 != value))
				{
					this._保险费总和 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_住宿费总和", DbType="Int")]
		public System.Nullable<int> 住宿费总和
		{
			get
			{
				return this._住宿费总和;
			}
			set
			{
				if ((this._住宿费总和 != value))
				{
					this._住宿费总和 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_书本费总和", DbType="Int")]
		public System.Nullable<int> 书本费总和
		{
			get
			{
				return this._书本费总和;
			}
			set
			{
				if ((this._书本费总和 != value))
				{
					this._书本费总和 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_其他费总和", DbType="Int")]
		public System.Nullable<int> 其他费总和
		{
			get
			{
				return this._其他费总和;
			}
			set
			{
				if ((this._其他费总和 != value))
				{
					this._其他费总和 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_减免总和", DbType="Int")]
		public System.Nullable<int> 减免总和
		{
			get
			{
				return this._减免总和;
			}
			set
			{
				if ((this._减免总和 != value))
				{
					this._减免总和 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_贷款总和", DbType="Int")]
		public System.Nullable<int> 贷款总和
		{
			get
			{
				return this._贷款总和;
			}
			set
			{
				if ((this._贷款总和 != value))
				{
					this._贷款总和 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_实缴总和", DbType="Int")]
		public System.Nullable<int> 实缴总和
		{
			get
			{
				return this._实缴总和;
			}
			set
			{
				if ((this._实缴总和 != value))
				{
					this._实缴总和 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_实收总和", DbType="Int")]
		public System.Nullable<int> 实收总和
		{
			get
			{
				return this._实收总和;
			}
			set
			{
				if ((this._实收总和 != value))
				{
					this._实收总和 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_总人数", DbType="Int")]
		public System.Nullable<int> 总人数
		{
			get
			{
				return this._总人数;
			}
			set
			{
				if ((this._总人数 != value))
				{
					this._总人数 = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Student_infor_view")]
	public partial class Student_infor_view
	{
		
		private string _studNo;
		
		private string _studName;
		
		private string _studSex;
		
		private string _studTel;
		
		private System.Nullable<System.DateTime> _studBirth;
		
		private string _deptName;
		
		private string _specName;
		
		private string _clasName;
		
		public Student_infor_view()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_studNo", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string studNo
		{
			get
			{
				return this._studNo;
			}
			set
			{
				if ((this._studNo != value))
				{
					this._studNo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_studName", DbType="VarChar(50)")]
		public string studName
		{
			get
			{
				return this._studName;
			}
			set
			{
				if ((this._studName != value))
				{
					this._studName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_studSex", DbType="VarChar(2)")]
		public string studSex
		{
			get
			{
				return this._studSex;
			}
			set
			{
				if ((this._studSex != value))
				{
					this._studSex = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_studTel", DbType="VarChar(15)")]
		public string studTel
		{
			get
			{
				return this._studTel;
			}
			set
			{
				if ((this._studTel != value))
				{
					this._studTel = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_studBirth", DbType="DateTime")]
		public System.Nullable<System.DateTime> studBirth
		{
			get
			{
				return this._studBirth;
			}
			set
			{
				if ((this._studBirth != value))
				{
					this._studBirth = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_deptName", DbType="VarChar(50)")]
		public string deptName
		{
			get
			{
				return this._deptName;
			}
			set
			{
				if ((this._deptName != value))
				{
					this._deptName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_specName", DbType="VarChar(50)")]
		public string specName
		{
			get
			{
				return this._specName;
			}
			set
			{
				if ((this._specName != value))
				{
					this._specName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_clasName", DbType="VarChar(50)")]
		public string clasName
		{
			get
			{
				return this._clasName;
			}
			set
			{
				if ((this._clasName != value))
				{
					this._clasName = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.studentPayInformation")]
	public partial class studentPayInformation
	{
		
		private System.Nullable<int> _Tuition;
		
		private System.Nullable<int> _Premiun;
		
		private System.Nullable<int> _Accom;
		
		private System.Nullable<int> _Book;
		
		private System.Nullable<int> _Other;
		
		private System.Nullable<int> _sTuiWaiver;
		
		private System.Nullable<int> _sLoans;
		
		public studentPayInformation()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tuition", DbType="Int")]
		public System.Nullable<int> Tuition
		{
			get
			{
				return this._Tuition;
			}
			set
			{
				if ((this._Tuition != value))
				{
					this._Tuition = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Premiun", DbType="Int")]
		public System.Nullable<int> Premiun
		{
			get
			{
				return this._Premiun;
			}
			set
			{
				if ((this._Premiun != value))
				{
					this._Premiun = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Accom", DbType="Int")]
		public System.Nullable<int> Accom
		{
			get
			{
				return this._Accom;
			}
			set
			{
				if ((this._Accom != value))
				{
					this._Accom = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Book", DbType="Int")]
		public System.Nullable<int> Book
		{
			get
			{
				return this._Book;
			}
			set
			{
				if ((this._Book != value))
				{
					this._Book = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Other", DbType="Int")]
		public System.Nullable<int> Other
		{
			get
			{
				return this._Other;
			}
			set
			{
				if ((this._Other != value))
				{
					this._Other = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sTuiWaiver", DbType="Int")]
		public System.Nullable<int> sTuiWaiver
		{
			get
			{
				return this._sTuiWaiver;
			}
			set
			{
				if ((this._sTuiWaiver != value))
				{
					this._sTuiWaiver = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sLoans", DbType="Int")]
		public System.Nullable<int> sLoans
		{
			get
			{
				return this._sLoans;
			}
			set
			{
				if ((this._sLoans != value))
				{
					this._sLoans = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Term_statistics_view")]
	public partial class Term_statistics_view
	{
		
		private string _学年;
		
		private System.Nullable<int> _学费总和;
		
		private System.Nullable<int> _保险费总和;
		
		private System.Nullable<int> _住宿费总和;
		
		private System.Nullable<int> _书本费总和;
		
		private System.Nullable<int> _其他费总和;
		
		private System.Nullable<int> _减免总和;
		
		private System.Nullable<int> _贷款总和;
		
		private System.Nullable<int> _实缴总和;
		
		private System.Nullable<int> _实收总和;
		
		private System.Nullable<int> _总人数;
		
		public Term_statistics_view()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_学年", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string 学年
		{
			get
			{
				return this._学年;
			}
			set
			{
				if ((this._学年 != value))
				{
					this._学年 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_学费总和", DbType="Int")]
		public System.Nullable<int> 学费总和
		{
			get
			{
				return this._学费总和;
			}
			set
			{
				if ((this._学费总和 != value))
				{
					this._学费总和 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_保险费总和", DbType="Int")]
		public System.Nullable<int> 保险费总和
		{
			get
			{
				return this._保险费总和;
			}
			set
			{
				if ((this._保险费总和 != value))
				{
					this._保险费总和 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_住宿费总和", DbType="Int")]
		public System.Nullable<int> 住宿费总和
		{
			get
			{
				return this._住宿费总和;
			}
			set
			{
				if ((this._住宿费总和 != value))
				{
					this._住宿费总和 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_书本费总和", DbType="Int")]
		public System.Nullable<int> 书本费总和
		{
			get
			{
				return this._书本费总和;
			}
			set
			{
				if ((this._书本费总和 != value))
				{
					this._书本费总和 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_其他费总和", DbType="Int")]
		public System.Nullable<int> 其他费总和
		{
			get
			{
				return this._其他费总和;
			}
			set
			{
				if ((this._其他费总和 != value))
				{
					this._其他费总和 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_减免总和", DbType="Int")]
		public System.Nullable<int> 减免总和
		{
			get
			{
				return this._减免总和;
			}
			set
			{
				if ((this._减免总和 != value))
				{
					this._减免总和 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_贷款总和", DbType="Int")]
		public System.Nullable<int> 贷款总和
		{
			get
			{
				return this._贷款总和;
			}
			set
			{
				if ((this._贷款总和 != value))
				{
					this._贷款总和 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_实缴总和", DbType="Int")]
		public System.Nullable<int> 实缴总和
		{
			get
			{
				return this._实缴总和;
			}
			set
			{
				if ((this._实缴总和 != value))
				{
					this._实缴总和 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_实收总和", DbType="Int")]
		public System.Nullable<int> 实收总和
		{
			get
			{
				return this._实收总和;
			}
			set
			{
				if ((this._实收总和 != value))
				{
					this._实收总和 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_总人数", DbType="Int")]
		public System.Nullable<int> 总人数
		{
			get
			{
				return this._总人数;
			}
			set
			{
				if ((this._总人数 != value))
				{
					this._总人数 = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TuiTion_seacher_view")]
	public partial class TuiTion_seacher_view
	{
		
		private string _院系;
		
		private string _专业;
		
		private string _班级;
		
		private string _学号;
		
		private string _学年号;
		
		private string _姓名;
		
		private System.Nullable<int> _学费;
		
		private System.Nullable<int> _保险费;
		
		private System.Nullable<int> _住宿费;
		
		private System.Nullable<int> _书本费;
		
		private System.Nullable<int> _其他费;
		
		private System.Nullable<int> _学费减免;
		
		private System.Nullable<int> _贷款;
		
		private System.Nullable<int> _实缴费;
		
		private System.Nullable<int> _实收费;
		
		private System.Nullable<System.DateTime> _缴费日期;
		
		public TuiTion_seacher_view()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_院系", DbType="VarChar(50)")]
		public string 院系
		{
			get
			{
				return this._院系;
			}
			set
			{
				if ((this._院系 != value))
				{
					this._院系 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_专业", DbType="VarChar(50)")]
		public string 专业
		{
			get
			{
				return this._专业;
			}
			set
			{
				if ((this._专业 != value))
				{
					this._专业 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_班级", DbType="VarChar(50)")]
		public string 班级
		{
			get
			{
				return this._班级;
			}
			set
			{
				if ((this._班级 != value))
				{
					this._班级 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_学号", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string 学号
		{
			get
			{
				return this._学号;
			}
			set
			{
				if ((this._学号 != value))
				{
					this._学号 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_学年号", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string 学年号
		{
			get
			{
				return this._学年号;
			}
			set
			{
				if ((this._学年号 != value))
				{
					this._学年号 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_姓名", DbType="VarChar(50)")]
		public string 姓名
		{
			get
			{
				return this._姓名;
			}
			set
			{
				if ((this._姓名 != value))
				{
					this._姓名 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_学费", DbType="Int")]
		public System.Nullable<int> 学费
		{
			get
			{
				return this._学费;
			}
			set
			{
				if ((this._学费 != value))
				{
					this._学费 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_保险费", DbType="Int")]
		public System.Nullable<int> 保险费
		{
			get
			{
				return this._保险费;
			}
			set
			{
				if ((this._保险费 != value))
				{
					this._保险费 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_住宿费", DbType="Int")]
		public System.Nullable<int> 住宿费
		{
			get
			{
				return this._住宿费;
			}
			set
			{
				if ((this._住宿费 != value))
				{
					this._住宿费 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_书本费", DbType="Int")]
		public System.Nullable<int> 书本费
		{
			get
			{
				return this._书本费;
			}
			set
			{
				if ((this._书本费 != value))
				{
					this._书本费 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_其他费", DbType="Int")]
		public System.Nullable<int> 其他费
		{
			get
			{
				return this._其他费;
			}
			set
			{
				if ((this._其他费 != value))
				{
					this._其他费 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_学费减免", DbType="Int")]
		public System.Nullable<int> 学费减免
		{
			get
			{
				return this._学费减免;
			}
			set
			{
				if ((this._学费减免 != value))
				{
					this._学费减免 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_贷款", DbType="Int")]
		public System.Nullable<int> 贷款
		{
			get
			{
				return this._贷款;
			}
			set
			{
				if ((this._贷款 != value))
				{
					this._贷款 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_实缴费", DbType="Int")]
		public System.Nullable<int> 实缴费
		{
			get
			{
				return this._实缴费;
			}
			set
			{
				if ((this._实缴费 != value))
				{
					this._实缴费 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_实收费", DbType="Int")]
		public System.Nullable<int> 实收费
		{
			get
			{
				return this._实收费;
			}
			set
			{
				if ((this._实收费 != value))
				{
					this._实收费 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_缴费日期", DbType="DateTime")]
		public System.Nullable<System.DateTime> 缴费日期
		{
			get
			{
				return this._缴费日期;
			}
			set
			{
				if ((this._缴费日期 != value))
				{
					this._缴费日期 = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Speciality_nopay_view")]
	public partial class Speciality_nopay_view
	{
		
		private string _专业;
		
		private string _学院;
		
		private System.Nullable<int> _学费欠费总额;
		
		private System.Nullable<int> _保险费欠费总额;
		
		private System.Nullable<int> _住宿费欠费总额;
		
		private System.Nullable<int> _书本费欠费总额;
		
		private System.Nullable<int> _其他费欠费总额;
		
		private System.Nullable<int> _减免欠费总额;
		
		private System.Nullable<int> _贷款欠费总额;
		
		private System.Nullable<int> _总人数;
		
		public Speciality_nopay_view()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_专业", DbType="VarChar(50)")]
		public string 专业
		{
			get
			{
				return this._专业;
			}
			set
			{
				if ((this._专业 != value))
				{
					this._专业 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_学院", DbType="VarChar(50)")]
		public string 学院
		{
			get
			{
				return this._学院;
			}
			set
			{
				if ((this._学院 != value))
				{
					this._学院 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_学费欠费总额", DbType="Int")]
		public System.Nullable<int> 学费欠费总额
		{
			get
			{
				return this._学费欠费总额;
			}
			set
			{
				if ((this._学费欠费总额 != value))
				{
					this._学费欠费总额 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_保险费欠费总额", DbType="Int")]
		public System.Nullable<int> 保险费欠费总额
		{
			get
			{
				return this._保险费欠费总额;
			}
			set
			{
				if ((this._保险费欠费总额 != value))
				{
					this._保险费欠费总额 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_住宿费欠费总额", DbType="Int")]
		public System.Nullable<int> 住宿费欠费总额
		{
			get
			{
				return this._住宿费欠费总额;
			}
			set
			{
				if ((this._住宿费欠费总额 != value))
				{
					this._住宿费欠费总额 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_书本费欠费总额", DbType="Int")]
		public System.Nullable<int> 书本费欠费总额
		{
			get
			{
				return this._书本费欠费总额;
			}
			set
			{
				if ((this._书本费欠费总额 != value))
				{
					this._书本费欠费总额 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_其他费欠费总额", DbType="Int")]
		public System.Nullable<int> 其他费欠费总额
		{
			get
			{
				return this._其他费欠费总额;
			}
			set
			{
				if ((this._其他费欠费总额 != value))
				{
					this._其他费欠费总额 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_减免欠费总额", DbType="Int")]
		public System.Nullable<int> 减免欠费总额
		{
			get
			{
				return this._减免欠费总额;
			}
			set
			{
				if ((this._减免欠费总额 != value))
				{
					this._减免欠费总额 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_贷款欠费总额", DbType="Int")]
		public System.Nullable<int> 贷款欠费总额
		{
			get
			{
				return this._贷款欠费总额;
			}
			set
			{
				if ((this._贷款欠费总额 != value))
				{
					this._贷款欠费总额 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_总人数", DbType="Int")]
		public System.Nullable<int> 总人数
		{
			get
			{
				return this._总人数;
			}
			set
			{
				if ((this._总人数 != value))
				{
					this._总人数 = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TuiTion_seacher_view_change")]
	public partial class TuiTion_seacher_view_change
	{
		
		private string _学院;
		
		private string _专业;
		
		private string _班级;
		
		private string _学号;
		
		private string _学年号;
		
		private string _姓名;
		
		private System.Nullable<int> _学费;
		
		private System.Nullable<int> _保险费;
		
		private System.Nullable<int> _住宿费;
		
		private System.Nullable<int> _书本费;
		
		private System.Nullable<int> _其他费;
		
		private System.Nullable<int> _学费减免;
		
		private System.Nullable<int> _贷款;
		
		private System.Nullable<int> _实缴费;
		
		private System.Nullable<int> _实收费;
		
		private string _缴费日期;
		
		public TuiTion_seacher_view_change()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_学院", DbType="VarChar(50)")]
		public string 学院
		{
			get
			{
				return this._学院;
			}
			set
			{
				if ((this._学院 != value))
				{
					this._学院 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_专业", DbType="VarChar(50)")]
		public string 专业
		{
			get
			{
				return this._专业;
			}
			set
			{
				if ((this._专业 != value))
				{
					this._专业 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_班级", DbType="VarChar(50)")]
		public string 班级
		{
			get
			{
				return this._班级;
			}
			set
			{
				if ((this._班级 != value))
				{
					this._班级 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_学号", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string 学号
		{
			get
			{
				return this._学号;
			}
			set
			{
				if ((this._学号 != value))
				{
					this._学号 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_学年号", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string 学年号
		{
			get
			{
				return this._学年号;
			}
			set
			{
				if ((this._学年号 != value))
				{
					this._学年号 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_姓名", DbType="VarChar(50)")]
		public string 姓名
		{
			get
			{
				return this._姓名;
			}
			set
			{
				if ((this._姓名 != value))
				{
					this._姓名 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_学费", DbType="Int")]
		public System.Nullable<int> 学费
		{
			get
			{
				return this._学费;
			}
			set
			{
				if ((this._学费 != value))
				{
					this._学费 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_保险费", DbType="Int")]
		public System.Nullable<int> 保险费
		{
			get
			{
				return this._保险费;
			}
			set
			{
				if ((this._保险费 != value))
				{
					this._保险费 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_住宿费", DbType="Int")]
		public System.Nullable<int> 住宿费
		{
			get
			{
				return this._住宿费;
			}
			set
			{
				if ((this._住宿费 != value))
				{
					this._住宿费 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_书本费", DbType="Int")]
		public System.Nullable<int> 书本费
		{
			get
			{
				return this._书本费;
			}
			set
			{
				if ((this._书本费 != value))
				{
					this._书本费 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_其他费", DbType="Int")]
		public System.Nullable<int> 其他费
		{
			get
			{
				return this._其他费;
			}
			set
			{
				if ((this._其他费 != value))
				{
					this._其他费 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_学费减免", DbType="Int")]
		public System.Nullable<int> 学费减免
		{
			get
			{
				return this._学费减免;
			}
			set
			{
				if ((this._学费减免 != value))
				{
					this._学费减免 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_贷款", DbType="Int")]
		public System.Nullable<int> 贷款
		{
			get
			{
				return this._贷款;
			}
			set
			{
				if ((this._贷款 != value))
				{
					this._贷款 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_实缴费", DbType="Int")]
		public System.Nullable<int> 实缴费
		{
			get
			{
				return this._实缴费;
			}
			set
			{
				if ((this._实缴费 != value))
				{
					this._实缴费 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_实收费", DbType="Int")]
		public System.Nullable<int> 实收费
		{
			get
			{
				return this._实收费;
			}
			set
			{
				if ((this._实收费 != value))
				{
					this._实收费 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_缴费日期", DbType="VarChar(50)")]
		public string 缴费日期
		{
			get
			{
				return this._缴费日期;
			}
			set
			{
				if ((this._缴费日期 != value))
				{
					this._缴费日期 = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
